spring.application.name=championcarteira

# Configuração do Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

# --- A MUDANÇA ESTÁ AQUI ---
# Mude de 'validate' para 'update' para ele CRIAR a tabela sozinho
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Batch de inserts/updates
spring.jpa.properties.hibernate.jdbc.batch_size=50

# Ordena inserts para melhorar o batch
spring.jpa.properties.hibernate.order_inserts=true

# Ordena updates também
spring.jpa.properties.hibernate.order_updates=true

# Necessário para entidades com ID auto increment (Postgres)
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Pool de conexões
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Segredo do JWT
api.security.token.secret=dsf65sd1fsd651f6d5s4fa6d5f468a4f5d